/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { EurPriceFeedMock } from "../EurPriceFeedMock";

export class EurPriceFeedMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EurPriceFeedMock> {
    return super.deploy(overrides || {}) as Promise<EurPriceFeedMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EurPriceFeedMock {
    return super.attach(address) as EurPriceFeedMock;
  }
  connect(signer: Signer): EurPriceFeedMock__factory {
    return super.connect(signer) as EurPriceFeedMock__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EurPriceFeedMock {
    return new Contract(address, _abi, signerOrProvider) as EurPriceFeedMock;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "assetEthFeed",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "_feed",
        type: "address",
      },
    ],
    name: "setAssetEthFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610122806100206000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80630bc2def414603757806367629ec6146064575b600080fd5b606260048036036040811015604b57600080fd5b506001600160a01b038135811691602001351660a3565b005b608760048036036020811015607857600080fd5b50356001600160a01b031660d1565b604080516001600160a01b039092168252519081900360200190f35b6001600160a01b03918216600090815260208190526040902080546001600160a01b03191691909216179055565b6000602081905290815260409020546001600160a01b03168156fea26469706673582212205c197b4798bdc7101931a07172b99689064c5cb9e4b0e0a7d60a26ad25d0544064736f6c63430007060033";
