/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IEurPriceFeed } from "../IEurPriceFeed";

export class IEurPriceFeed__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEurPriceFeed {
    return new Contract(address, _abi, signerOrProvider) as IEurPriceFeed;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "assetEthFeed",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
