/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { XTokenWrapperMock } from "../XTokenWrapperMock";

export class XTokenWrapperMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<XTokenWrapperMock> {
    return super.deploy(overrides || {}) as Promise<XTokenWrapperMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): XTokenWrapperMock {
    return super.attach(address) as XTokenWrapperMock;
  }
  connect(signer: Signer): XTokenWrapperMock__factory {
    return super.connect(signer) as XTokenWrapperMock__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): XTokenWrapperMock {
    return new Contract(address, _abi, signerOrProvider) as XTokenWrapperMock;
  }
}

const _abi = [
  {
    inputs: [],
    name: "ETH_TOKEN_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "tokenToXToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060e38061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80631878d1f114603757806327009c75146059575b600080fd5b603d607c565b604080516001600160a01b039092168252519081900360200190f35b603d60048036036020811015606d57600080fd5b50356001600160a01b03166094565b73eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee81565b5073eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee9056fea26469706673582212201fee7d6a8fad4a7adb62f5b9b42cbe6d50e77cc1aeb584f8fddb4fa10ef712c964736f6c63430007060033";
