/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface EurPriceFeedMockInterface extends ethers.utils.Interface {
  functions: {
    "assetEthFeed(address)": FunctionFragment;
    "setAssetEthFeed(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assetEthFeed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetEthFeed",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "assetEthFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetEthFeed",
    data: BytesLike
  ): Result;

  events: {};
}

export class EurPriceFeedMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EurPriceFeedMockInterface;

  functions: {
    assetEthFeed(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    "assetEthFeed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setAssetEthFeed(
      _asset: string,
      _feed: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAssetEthFeed(address,address)"(
      _asset: string,
      _feed: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  assetEthFeed(arg0: string, overrides?: CallOverrides): Promise<string>;

  "assetEthFeed(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  setAssetEthFeed(
    _asset: string,
    _feed: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAssetEthFeed(address,address)"(
    _asset: string,
    _feed: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    assetEthFeed(arg0: string, overrides?: CallOverrides): Promise<string>;

    "assetEthFeed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    setAssetEthFeed(
      _asset: string,
      _feed: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAssetEthFeed(address,address)"(
      _asset: string,
      _feed: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    assetEthFeed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "assetEthFeed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAssetEthFeed(
      _asset: string,
      _feed: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAssetEthFeed(address,address)"(
      _asset: string,
      _feed: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assetEthFeed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetEthFeed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAssetEthFeed(
      _asset: string,
      _feed: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAssetEthFeed(address,address)"(
      _asset: string,
      _feed: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
